version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build:
    docker: 
      - image: circleci/node:8.17
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - firebase-deploy/deploy:
          token: "${FIREBASE_DEPLOY_TOKEN_D}"