version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build:
    docker: 
      - image: circleci/node:8.17
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
  deploy:
    docker:
      - image: circleci/node:8.17
    steps:
      - checkout
      - firebase-deploy/deploy:
          token: "${FIREBASE_DEPLOY_TOKEN_D}"

workflows:
  build_only:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^feature\/.+/
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
