version: 2.1
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  lint:
    docker: 
      - image: circleci/node:8.17
    steps:
      - checkout
      - run: npm install
      - run: npm run lintToJs
      - run: npm run codeFormatToHtml
  deploy:
    docker:
      - image: circleci/node:8.17
    steps:
      - checkout
      - run: npm install
      - run: npm run buildCss
      - firebase-deploy/deploy:
          token: "${FIREBASE_DEPLOY_TOKEN_D}"

workflows:
  lint_only:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - /^feature\/.+/
  lint_and_deploy:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
